[theme]
base = "light"
primaryColor = "#7452d6"
backgroundColor = "#f8f7fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#232238"
font = "sans serif"

[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false
